from .filesystem import ensure_directory, write_text

DEFAULT_DIRECTORIES = ("backend","frontend","database","docs","templates","assets","scripts","exports")

def generate_project(config):
    root = config.output_directory / config.project_name
    ensure_directory(root)
    for name in DEFAULT_DIRECTORIES:
        ensure_directory(root / name)
        write_text(root / name / ".gitkeep", "")
    write_text(root / "README.md", f"# {config.project_name}\n\nGenerated by CareerOS Forge.\n")
    write_text(root / ".gitignore", "__pycache__/\n.env\n*.sqlite\nnode_modules/\n")
    return root
